version: '3'

services:
  web:
    build: .
    command: python manage.py runserver
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: confs.settings.dev
    volumes:
      - ./:/usr/src/app
